// src/components/RegistrationForm.vue
<template>
  <form 
    @submit.prevent="handleRegistration" 
    class="bg-amber-100 shadow-md rounded px-8 pt-6 pb-8 mb-4"
    aria-label="Registration Form"
    >
    <div v-if="errorMessage" class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-4" role="alert">
      {{ errorMessage }}
    </div>
    <div>
      <label class="block text-gray-700 text-sm font-bold mt-4 mb-2" for="name">Name:</label>
      <input 
        class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" 
        type="text" 
        id="name" 
        v-model="formData.name"
        aria-required="true"
        aria-label="Name" 
        required>
    </div>
    <div>
      <label class="block text-gray-700 text-sm font-bold mt-4 mb-2" for="email">Email:</label>
      <input 
        class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" 
        type="email" 
        id="email" 
        v-model="formData.email"
        aria-required="true"
        aria-label="Email" 
        required>
    </div>
    <div>
      <label class="block text-gray-700 text-sm font-bold mt-4 mb-2" for="password">Password:</label>
      <input 
        class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" 
        type="password" 
        id="password" 
        v-model="formData.password" 
        aria-required="true"
        aria-label="Password"
        required>
    </div>
    <div class="flex items-center justify-between mt-6">
      <button 
        class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" 
        type="submit"
        aria-label="Register User"
        >
        Register
      </button>
    </div>
  </form>
</template>

<script setup>
import axios from 'axios';
import { ref } from 'vue';
import { useRouter } from 'vue-router';

const router = useRouter();

const formData = {
  name: '',
  email: '',
  password: ''
};

const errorMessage = ref('');

//Handles the registration process
const handleRegistration = async () => {
  try {

    await axios.post('http://localhost:3000/users', formData);

     // Clear the form data after successful registration
    formData.value = { name: '', email: '', password: '' };


    router.push('/login');

  } catch (error) {
     errorMessage.value = 'Failed to register your account, Please try again.';
    console.error('Error registering user:', error);
  }
};
</script>

// gimme-more-project/src/components/RegistrationForm/RegistrationForm.tsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import MessageText from '../MessageText/MessageText';

const RegistrationForm = () => {
    const [firstName, setFirstName] = useState('');
    const [lastName, setLastName] = useState('');
    const [email, setEmail] = useState('');
    const [dob, setDob] = useState('');
    const [password, setPassword] = useState('');
    const [repeatPassword, setRepeatPassword] = useState('');
    const [passwordMatchError, setPasswordMatchError] = useState(false);

    const [successMessage, setSuccessMessage] = useState('');
    const [errorMessage, setErrorMessage] = useState('');

    const navigate = useNavigate();

    const handleRegister = async () => {
        try {
            if (password !== repeatPassword) {
                setPasswordMatchError(true);
                return;
            }

            const response = await fetch('http://localhost:4000/register', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                    firstName,
                    lastName,
                    email,
                    dob,
                    password,
                }),
            });

            if (response.ok) {
                setErrorMessage('')
                setSuccessMessage('Registered successfully')
                setTimeout(() => {
                    navigate('/login')
                }, 500)
            } else {
                setErrorMessage('Registration failed');
            }
        } catch (error: any) {
            setErrorMessage('Error during registration');
        }
    };

    return (
        <div className="max-w-md mx-auto mt-8 p-4 rounded-md" style={{ backgroundColor: '#2A5996' }}>
            <h2 className="text-3xl font-semibold mb-4 text-center text-white">Registration</h2>
            <form className="flex flex-col space-y-4">
                <label className="flex flex-col">
                    <span className="text-white">First Name:</span>
                    <input
                        type="text"
                        value={firstName}
                        onChange={(e) => setFirstName(e.target.value)}
                        className="mt-1 p-2 border border-gray-300 rounded-md focus:outline-none focus:ring focus:border-blue-500"
                    />
                </label>
                <label className="flex flex-col">
                    <span className="text-white">Last Name:</span>
                    <input
                        type="text"
                        value={lastName}
                        onChange={(e) => setLastName(e.target.value)}
                        className="mt-1 p-2 border border-gray-300 rounded-md focus:outline-none focus:ring focus:border-blue-500"
                    />
                </label>
                <label className="flex flex-col">
                    <span className="text-white">Email:</span>
                    <input
                        type="email"
                        value={email}
                        onChange={(e) => setEmail(e.target.value)}
                        className="mt-1 p-2 border border-gray-300 rounded-md focus:outline-none focus:ring focus:border-blue-500"
                    />
                </label>
                <label className="flex flex-col">
                    <span className="text-white">Date of Birth:</span>
                    <input
                        type="date"
                        value={dob}
                        onChange={(e) => setDob(e.target.value)}
                        className="mt-1 p-2 border border-gray-300 rounded-md focus:outline-none focus:ring focus:border-blue-500"
                    />
                </label>
                <label className="flex flex-col">
                    <span className="text-white">Password:</span>
                    <input
                        type="password"
                        value={password}
                        onChange={(e) => setPassword(e.target.value)}
                        className="mt-1 p-2 border border-gray-300 rounded-md focus:outline-none focus:ring focus:border-blue-500"
                    />
                </label>
                <label className="flex flex-col">
                    <span className="text-white">Repeat Password:</span>
                    <input
                        type="password"
                        value={repeatPassword}
                        onChange={(e) => {
                            setRepeatPassword(e.target.value);
                            setPasswordMatchError(false);
                        }}
                        className="mt-1 p-2 border border-gray-300 rounded-md focus:outline-none focus:ring focus:border-blue-500"
                    />
                </label>
                {passwordMatchError && <p className="text-red-500">Passwords do not match</p>}
                <button
                    type="button"
                    onClick={handleRegister}
                    className="bg-green-500 text-white p-2 rounded-md hover:bg-green-600 focus:outline-none focus:ring focus:border-green-300"
                >
                    Register
                </button>
            </form>
            {successMessage && <MessageText message={successMessage} type='success' />}
            {errorMessage && <MessageText message={errorMessage} type='error' />}
        </div>
    );
};

export default RegistrationForm;
