// gimme-more-project/src/components/LoginForm/LoginForm.tsx
import React, { useState } from 'react';
import axios from 'axios';
import { useNavigate } from 'react-router-dom';
import { setCookie } from '../../utils/cookies';
import MessageText from '../MessageText/MessageText'

const LoginForm = () => {
    const navigate = useNavigate();
    const [username, setUsername] = useState('');
    const [password, setPassword] = useState('');
    const [successMessage, setSuccessMessage] = useState('');
    const [errorMessage, setErrorMessage] = useState('');

    const handleLogin = async () => {
        try {
            const response = await axios.post('http://localhost:4000/login', {
                username,
                password,
            });

            if (response.data.success) {
                setCookie('user', JSON.stringify(response.data.user.firstName), 1);
                setErrorMessage('')
                setSuccessMessage('Successfully logged in')
                setTimeout(() => {
                    navigate('/')
                }, 500)
            } else {
                setErrorMessage('Your email and password does not match. Please try again.')
            }
        } catch (error: any) {
            setErrorMessage('Your email and password does not match. Please try again.')
        }
    };

    return (
        <div className="max-w-md mx-auto mt-8 p-4 pb-10 shadow-md rounded-md" style={{ backgroundColor: '#2A5996' }}>
            <h2 className="text-3xl font-semibold mb-4 text-center text-white">Login</h2>
            <form className="flex flex-col space-y-4">
                <label className="flex flex-col">
                    <span className="text-white">Username:</span>
                    <input
                        type="text"
                        value={username}
                        onChange={(e) => setUsername(e.target.value)}
                        className="mt-1 p-2 border border-gray-300 rounded-md focus:outline-none focus:ring focus:border-blue-500"
                    />
                </label>
                <label className="flex flex-col">
                    <span className="text-white">Password:</span>
                    <input
                        type="password"
                        value={password}
                        onChange={(e) => setPassword(e.target.value)}
                        className="mt-1 p-2 border border-gray-300 rounded-md focus:outline-none focus:ring focus:border-blue-500"
                    />
                </label>
                <button
                    type="button"
                    onClick={handleLogin}
                    className="bg-green-500 text-white p-2 rounded-md hover:bg-green-600 focus:outline-none focus:ring focus:border-green-300"
                >
                    Login
                </button>
            </form>
            {successMessage && <MessageText message={successMessage} type='success' />}
            {errorMessage && <MessageText message={errorMessage} type='error' /> }
        </div>
    );
};

export default LoginForm;

// src/components/LoginForm.vue
<template>
  <form 
    @submit.prevent="handleLogin" 
    class="bg-amber-100 w-full shadow-md rounded flex-1 px-8 pt-6 pb-8 mb-4"
    aria-label="Login Form" >
    <div v-if="errorMessage" class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-4" role="alert">
      {{ errorMessage }}
    </div>
    <div>
      <label class="block text-gray-700 text-sm font-bold mt-4 mb-2" for="email">Email:</label>
      <input 
        class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" 
        type="email" 
        id="email" 
        v-model="formData.email"
        aria-label="Email Address" 
        aria-required="true" 
        required>
    </div>
    <div>
      <label class="block text-gray-700 text-sm font-bold mt-4 mb-2" for="password">Password:</label>
      <input 
        class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" 
        id="password" 
        v-model="formData.password" 
        type="password"
        aria-label="Password" 
        aria-required="true" 
        required>
    </div>
    <div class="flex items-center justify-between mt-6">
      <button 
        class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" 
        type="submit" 
        aria-label="Submit Log in">
          Log In
      </button>
    </div>
  </form>
</template>

<script setup>
import { useUserStore } from '@/stores/user';
import { useRouter } from 'vue-router';
import { ref } from 'vue';
const router = useRouter();

const userStore = useUserStore();
const errorMessage = ref('');
const formData = {
  email: '',
  password: ''
};

const handleLogin = async () => {
  try {
    // Call the login action from the authentication store
    await userStore.login(formData.email, formData.password);
    // Clear the form after successful login
    formData.email = '';
    formData.password = '';
    router.push('/');

  } catch (error) {
    console.error('Error logging in:', error);
    errorMessage.value = 'Failed to log in. Please check your credentials and try again.';
  }
};
</script>
